### PR TITLE
Evaluate correct position letters first (fixes #8)

### LINKED ISSUE #8: Duplicate letter guesses not evaluated in the correct order (1/25/22 spoilers)
Puzzle to reproduce: https://ember-wordle.pages.dev/2022-01-25

If you guess a double letter where the first is in the wrong position second is in the correct position, the game incorrectly reports the first as yellow and the second as grey. 
image

Instead, the first should show as grey and the second as green.
image

### PR DESCRIPTION
**Pull request by adamkiczula**
* Ensures that letters in the correct position are evaluated before correct guesses in the wrong position.
* Also fixed typo `Occurance` -> `Occurrence`

### CODE REVIEW

File: app/components/board/state/actions.ts [hunk 1]
```diff
@@ -154,3 +144,26 @@ function getLetterOccurances(word: string) {
...
+
+function checkOccurrences(
+  attempt: Attempt,
+  answer: string,
+  answerOccurrences: Record<string, number>,
+  checkPosition: boolean
+) {
+  attempt.letters.forEach((letter, index) => {
+    let occurrences = answerOccurrences[letter.value];
+    let word = wordFor(attempt);
```
Comment (NullVoxPopuli) [inline app/components/board/state/actions.ts:156]: Since nothing is changing here each iteration, this could come out of the roop

**Comment by NullVoxPopuli** [comment]
Nice! Thanks for this! I like how the main function reads now!
