### PR TITLE
Ensure isInCorrectPosition based on the current letter position (Fixes #6)

### LINKED ISSUE #6: 🐛: Improperly marks duplicate letters green
AFDF3B4D-1FC0-4923-95AF-C2259996FD92

If the same letter appears twice, both appearances will be marked green even if that’s not quite correct.

### PR DESCRIPTION
**Pull request by gitKrystan**

### CODE REVIEW

File: app/components/board/state/actions.ts [hunk 1]
```diff
@@ -109,19 +109,19 @@ export function guess(attempt: Attempt, { answer, all, onError, onWin }: GuessOp
...
+  attempt.letters.forEach((letter, index) => {
     let occurances = answerOccurances[letter.value];
 
     if (occurances) {
       answerOccurances[letter.value]--;
 
       letter.isInAnswer = true;
 
-      if (answer.indexOf(letter.value) === word.indexOf(letter.value)) {
+      if (answer[index] === word[index]) {
```
Comment (NullVoxPopuli) [inline app/components/board/state/actions.ts:120]: ooo nice!!

**Comment by NullVoxPopuli** [comment]
Thank you!!!!!

**Comment by gitKrystan** [comment]
No problem! This was my first time using the ember-template-imports syntax, and I really enjoyed it. I hope you are planning to submit an EmberConf talk proposal for "How I built a Wordle clone using template imports" because I learned a bunch reading this code!
